<?php include 'header.php'; ?>
<link  rel="stylesheet" href="./css/custom.css">
<script src="./js/customs.js"></script>



<div class="carousel fade-carousel slide new_pdf" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <!-- Indicators -->
   <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1">
          <div class="overlay"></div>
      </div>
      <div class="hero">
        <hgroup>
            <h2>CRITERIA-6</h2>        
           
        </hgroup>
        
      </div>
    </div>
     </div> 
</div>
       
<div class="container new_pdf" style="box-shadow:-3px 5px 15px #000;     padding: 47px 30px;">
  <!--<ul class="nav nav-tabs" role="tablist" width="90%" style="background-color: #f7f7f7;">-->
  <!--  <li class="nav-item" style="color: rgb(0, 0, 255);">-->
  <!--    <a class="nav-link active" data-toggle="tab" href="NAAC/4.1.1.pdf" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.1.1.1</b></a>-->
  <!--  </li>-->
  <!--  <li class="nav-item">-->
  <!--    <a class="nav-link" data-toggle="tab" href="#menu1" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.2.1</b></a>-->
  <!--  </li>-->
  <!--  <li class="nav-item">-->
  <!--    <a class="nav-link" data-toggle="tab" href="#menu2"><b style="font-size:16px;color:rgb(120, 120, 120)">4.3.1</b></a>-->
  <!--  </li>-->
  <!--   <li class="nav-item">-->
  <!--     </ul>-->
       
 
  <!-- Tab panes -->
   
   
<div class="col-md-12">
    <div class="accordion " id="accordionExample">
       <div class="card">
  
          <div id="collapseCriterionI" class="collapse show" aria-labelledby="headingCriterionI" data-parent="#accordionExample" style="">
             <div class="card-body">
                <div class="accordion" id="accordionExample2">
                   <div class="card">
                      <div class="card-header" id="heading6.2.2">
                         <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse111" aria-expanded="true" aria-controls="collapse111" style="font-weight:bold;font-size:15px;">
                            6.2.2                                </button>
                         </h2>
                      </div>
                      <div id="collapse111" class="collapse" aria-labelledby="heading111" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./SSR/Criterion-6/6.2.2(1).pdf" >6.2.2(1)Policy on E-Goverence</a></li>
			       <li><a href="./SSR/Criterion-6/6.2.2(2).pdf" >6.2.2(2)Invoices</a></li>
                               <li><a href="./SSR/Criterion-6/6.2.2(3).pdf" >6.2.2(3)Screenshots</a></li>
			       <li><a href="./SSR/Criterion-6/6.2.2(4).pdf" >6.2.2(4)ERP Document</a></li>
			       <li><a href="./SSR/Criterion-6/6.2.2(5).pdf" >6.2.2(5)Annual Report</a></li>
</ul>
                         </div>
                      </div>
                   </div>
                   <div class="card">
                      <div class="card-header" id="heading6.3.2">
                         <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse121" aria-expanded="true" aria-controls="collapse121" style="font-weight:bold;font-size:15px;">
                            6.3.2                                </button>
                         </h2>
                      </div>
                      <div id="collapse121" class="collapse" aria-labelledby="heading121" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./SSR/Criterion-6/6.3.2(1).pdf">6.3.2(1)Policy Document </a></li>
			       <li><a href="./SSR/Criterion-6/6.3.2(2).pdf">6.3.2(2)List of teachers benefited by Financial support for A.Y 2021-22</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.2(3).pdf" >6.3.2(3)List of teachers benefited by Financial support for A.Y- 2020-21</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.2(4).pdf" >6.3.2(4)List of teachers benefited by Financial support for A.Y- 2019-20</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.2(5).pdf" >6.3.2(5)List of teachers benefited by Financial support for A.Y-2018-19</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.2(6).pdf" >6.3.2(6)List of teachers benefited by Financial support for A.Y-2017-18</a></li>
			       <li><a href="./SSR/Criterion-6/6.3.2(7).pdf" >6.3.2(7)Audited Statements</a></li>
                            </ul>
                         </div>
                      </div>
                   </div>
                   <div class="card">
                      <div class="card-header" id="heading6.3.3">
                         <h2 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse122" aria-expanded="false" aria-controls="collapse122" style="font-weight:bold;font-size:15px;">
                            6.3.3                                </button>
                         </h2>
                      </div>
                      <div id="collapse122" class="collapse" aria-labelledby="heading122" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./SSR/Criterion-6/6.3.3(1).pdf" >6.3.3(1)Professional Development program for AY 2021-22</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.3(2).pdf" >6.3.3(2)Professional Development program for AY 2020-21</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.3(3).pdf" >6.3.3(3)Professional Development program for AY 2019-20</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.3(4).pdf" >6.3.3(4)Professional Development program for AY 2018-19</a></li>
                               <li><a href="./SSR/Criterion-6/6.3.3(5).pdf" >6.3.3(5)Professional Development program for AY 2017-18</a></li>
                            </ul>
                         </div>
                      </div>
                   </div>
                   <div class="card">
                      <div class="card-header" id="heading6.5.2">
                         <h2 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse131" aria-expanded="false" aria-controls="collapse131" style="font-weight:bold;font-size:15px;">
                            6.5.2                                </button>
                         </h2>
                      </div>
                      <div id="collapse131" class="collapse" aria-labelledby="heading131" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./SSR/Criterion-6/6.5.2(1).pdf" >6.5.2(1)MInutes of IQAC</a></li>
			       <li><a href="./SSR/Criterion-6/6.5.2(2).pdf" >6.5.2(2)Feedback analysis and Action taken report</a></li>
			       <li><a href="./SSR/Criterion-6/6.5.2(3).pdf">6.5.2(3)E-Copies of Collaborations with other Institution</a></li>
			       <li><a href="./SSR/Criterion-6/6.5.2(4).pdf">6.5.2(4)List of collabrative activities with other institution</a></li>
			       <li><a href="./SSR/Criterion-6/6.5.2(5).pdf">6.5.2(5)ISO Certificate</a></li>
                            </ul>
                         </div>
                      </div>
                 
                            </ul>
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
    
     
    <!-- your content -->


 </div>
   
   

    </div>
    </div>

     <div id="menu3" class="container tab-pane fade">
     <!-- <h3>Menu 3</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu4" class="container tab-pane fade">
     <!-- <h3>Menu 4</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu5" class="container tab-pane fade">
     <!-- <h3>Menu 5</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu6" class="container tab-pane fade">
     <!-- <h3>Menu 6</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
  </div>
</div>
<br><br>



<?php include 'footer.php';?>