<?php include 'header.php'; ?>
<link  rel="stylesheet" href="./css/custom.css">
<div class="carousel fade-carousel slide new_pdf" data-ride="carousel" data-interval="4000" id="bs-carousel">
   <!-- Overlay -->
   <!-- Indicators -->
   <!-- Wrapper for slides -->
   <div class="carousel-inner">
      <div class="item slides active">
         <div class="slide-1">
            <div class="overlay"></div>
         </div>
         <div class="hero">
            <hgroup>
               <h2>DVV-CRITERIA-5</h2>
            </hgroup>
         </div>
      </div>
   </div>
</div>
<div class="container new_pdf" style="box-shadow:-3px 5px 15px #000;     padding: 47px 30px;">
   <!--<ul class="nav nav-tabs" role="tablist" width="90%" style="background-color: #f7f7f7;">-->
   <!--  <li class="nav-item" style="color: rgb(0, 0, 255);">-->
   <!--    <a class="nav-link active" data-toggle="tab" href="NAAC/4.1.1.pdf" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.1.1.1</b></a>-->
   <!--  </li>-->
   <!--  <li class="nav-item">-->
   <!--    <a class="nav-link" data-toggle="tab" href="#menu1" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.2.1</b></a>-->
   <!--  </li>-->
   <!--  <li class="nav-item">-->
   <!--    <a class="nav-link" data-toggle="tab" href="#menu2"><b style="font-size:16px;color:rgb(120, 120, 120)">4.3.1</b></a>-->
   <!--  </li>-->
   <!--   <li class="nav-item">-->
   <!--     </ul>-->
   <!-- Tab panes -->
   <div class="col-md-12">
      <div class="accordion " id="accordionExample">
         <div class="card">
            <div id="collapseCriterionI" class="collapse show" aria-labelledby="headingCriterionI" data-parent="#accordionExample" style="">
               <div class="card-body">
                  <div class="accordion" id="accordionExample2">
                     <div class="card">
                        <div class="card-header" id="heading5.1.1">
                           <h2 class="mb-0">
                              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse111" aria-expanded="true" aria-controls="collapse111" style="font-weight:bold;font-size:15px;">
                              5.1.1                                </button>
                           </h2>
                        </div>
                        <div id="collapse111" class="collapse" aria-labelledby="heading111" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                              <ul>
                                 <li><a href="./DVV/C-5DVV/5.1.1(1).pdf" >5.1.1(1)Sanction letters along with the list of students benefitted by Government scholarships in the A.Y.2021-22</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.1(2).pdf" >5.1.1(2)Sanction letters along with the list of students benefitted by Government scholarships in the A.Y.2020-21</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.1(3).pdf" >5.1.1(3)Sanction letters along with the list of students benefitted by Government scholarships in the A.Y.2019-20</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.1(4).pdf" >5.1.1(4)Sanction letters along with the list of students benefitted by Government scholarships in the A.Y.2018-19</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.1(5).pdf" >5.1.1(5)Sanction letters along with the list of students benefitted by Government scholarships in the A.Y.2017-18</a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.1.2">
                           <h2 class="mb-0">
                              <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse121" aria-expanded="true" aria-controls="collapse121" style="font-weight:bold;font-size:15px;">
                              5.1.2                                </button>
                           </h2>
                        </div>
                        <div id="collapse121" class="collapse" aria-labelledby="heading121" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                              <ul>
                                 <li><a href="./DVV/C-5DVV/5.1.2(1).pdf" >5.1.2(1)Photographs of all schemes during the assessment period</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.2(2).pdf" >5.1.2(2)Reports of all schemes during the assessment period</a></li>
                             </ul>
                           </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.1.3">
                           <h2 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse122" aria-expanded="false" aria-controls="collapse122" style="font-weight:bold;font-size:15px;">
                              5.1.3                                </button>
                           </h2>
                        </div>
                        <div id="collapse122" class="collapse" aria-labelledby="heading122" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                              <ul>
                                 <li><a href="./DVV/C-5DVV/5.1.3(1).pdf" >5.1.3.(1)Document for related to guidance for Competative Exam and Career Counselling AY 2021-22</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.3(2).pdf" >5.1.3.(2)Document for related to guidance for Competative Exam and Career Counselling AY 2020-21</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.3(3).pdf" >5.1.3.(3)Document for related to guidance for Competative Exam and Career Counselling AY 2019-20</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.3(4).pdf" >5.1.3.(4)Document for related to guidance for Competative Exam and Career Counselling AY 2018-19</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.3(5).pdf" >5.1.3.(5)Document for related to guidance for Competative Exam and Career Counselling AY 2017-18</a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.1.4">
                           <h2 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse131" aria-expanded="false" aria-controls="collapse131" style="font-weight:bold;font-size:15px;">
                              5.1.4                                </button>
                           </h2>
                        </div>
                        <div id="collapse131" class="collapse" aria-labelledby="heading131" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                              <ul>
                                 <li><a href="./DVV/C-5DVV/5.1.4(1).pdf" >5.1.4(1) Minutes of ANTI RAGGING</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.4(2).pdf">5.1.4(2) Minutes of WOMEN PROTECTION CELL</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.4(3).pdf">5.1.4(3) Grievance Redressel Committe</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.4(4).pdf">5.1.4(4) Sample undertaking form</a></li>
                                 <li><a href="./DVV/C-5DVV/5.1.4(5).pdf" >5.1.4(5) Weblink for online grievance cell</a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.2.1">
                           <h2 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse132" aria-expanded="false" aria-controls="collapse132" style="font-weight:bold;font-size:15px;">
                              5.2.1                                </button>
                           </h2>
                        </div>
                        <div id="collapse132" class="collapse" aria-labelledby="heading132" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                              <ul>
                                 <li><a href="./DVV/C-5DVV/5.2.1(1).pdf" >5.2.1(1)Placement Cell Annual Report</a></li>
                                 <li><a href="./DVV/C-5DVV/5.2.1(2).pdf" >5.2.1(2)Brochures and tie-ups of Placement Cell</a></li>
                                 <li><a href="./DVV/C-5DVV/5.2.1(3).pdf" >5.2.1(3)List of students progressed for higher education along with the documents during the assessment period</a></li>
                            </ul>
                           </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.2.2">
                           <h2 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse141" aria-expanded="false" aria-controls="collapse141" style="font-weight:bold;font-size:15px;">
                              5.2.2                                </button>
                           </h2>
                        </div>
                        <div id="collapse141" class="collapse" aria-labelledby="heading141" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                              <ul>
                                 <li><a href="./DVV/C-5DVV/5.2.2(1).pdf" >5.2.2 (1)List of qualified students along with their qualifying certificates in the A.Y.2021-22</a></li>
                                 <li><a href="./DVV/C-5DVV/5.2.2(2).pdf" >5.2.2 (2)List of qualified students along with their qualifying certificates in the A.Y.2020-21</a></li>
                                 <li><a href="./DVV/C-5DVV/5.2.2(3).pdf" >5.2.2 (3)List of qualified students along with their qualifying certificates in the A.Y.2019-20</a></li>
                                 <li><a href="./DVV/C-5DVV/5.2.2(4).pdf" >5.2.2 (4)List of qualified students along with their qualifying certificates in the A.Y.2018-19</a></li>
                        </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.2.2">
                           <h2 class="mb-0">
                              <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse171" aria-expanded="false" aria-controls="collapse171" style="font-weight:bold;font-size:15px;">
                        5.3.1                                </button>
                           </h2>
                        </div>
                        <div id="collapse171" class="collapse" aria-labelledby="heading171" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                               <ul>
                           <li><a href="./DVV/C-5DVV/5.3.1(1).pdf" >5.3.1(1)List of students along with the e-copies of award letters for A.Y.2021-22</a></li>
                           <li><a href="./DVV/C-5DVV/5.3.1(2).pdf" >5.3.1(2)List of students along with the e-copies of award letters for A.Y.2020-21</a></li>
                           <li><a href="./DVV/C-5DVV/5.3.1(3).pdf" >5.3.1(3)List of students along with the e-copies of award letters for A.Y.2019-20</a></li>
                           <li><a href="./DVV/C-5DVV/5.3.1(4).pdf" >5.3.1(4)List of students along with the e-copies of award letters for A.Y.2018-19</a></li>
                           <li><a href="./DVV/C-5DVV/5.3.1(5).pdf" >5.3.1(5)List of students along with the e-copies of award letters for A.Y.2017-18</a></li>
                            </ul>
                           </div>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header" id="heading5.2.2">
                           <h2 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse172" aria-expanded="false" aria-controls="collapse172" style="font-weight:bold;font-size:15px;">
                     5.3.2                                </button>
                           </h2>
                        </div>
                        <div id="collapse172" class="collapse" aria-labelledby="heading172" data-parent="#accordionExample2" style="">
                           <div class="card-body">
                               <ul>
                        <li><a href="./DVV/C-5DVV/5.3.2(1).pdf" >5.3.2(1)List of sports/cultural events along with list of participants in the A.Y.2021-22</a></li>
                        <li><a href="./DVV/C-5DVV/5.3.2(2).pdf" >5.3.2(2)List of sports/cultural events along with list of participants in the A.Y.2020-21</a></li>
                        <li><a href="./DVV/C-5DVV/5.3.2(3).pdf" >5.3.2(3)List of sports/cultural events along with list of participants in the A.Y.2019-20</a></li>
                        <li><a href="./DVV/C-5DVV/5.3.2(4).pdf" >5.3.2(4)List of sports/cultural events along with list of participants in the A.Y.2018-19</a></li>
                        <li><a href="./DVV/C-5DVV/5.3.2(5).pdf" >5.3.2(5)List of sports/cultural events along with list of participants in the A.Y.2017-18</a></li>
                     </ul>
                           </div>
                        </div>
                     </div>
                     
               </div>
            </div>
         </div>
      </div>
   </div>

<div id="menu3" class="container tab-pane fade">
   <!-- <h3>Menu 3</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
</div>
<div id="menu4" class="container tab-pane fade">
   <!-- <h3>Menu 4</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
</div>
<div id="menu5" class="container tab-pane fade">
   <!-- <h3>Menu 5</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
</div>
<div id="menu6" class="container tab-pane fade">
   <!-- <h3>Menu 6</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
</div>

<script>
   var acc = document.getElementsByClassName("accordion");
   var i;
   
   for (i = 0; i < acc.length; i++) {
     acc[i].addEventListener("click", function() {
       this.classList.toggle("active");
       var panel = this.nextElementSibling;
       if (panel.style.display === "block") {
         panel.style.display = "none";
       } else {
         panel.style.display = "block";
       }
     });
   }
</script>
<?php include 'footer.php';?>