<?php include 'header.php'; ?>
<style>
  .new_pdf  .card-body {
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1.25rem;
}

.new_pdf .accordion {
    overflow-anchor: none;
}
.new_pdf .accordion>.card:not(:last-of-type) {
    border-bottom: 0;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
}

.new_pdf .card {
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid rgba(0,0,0,.125);
    border-radius: .25rem;
}
.new_pdf .accordion>.card>.card-header {
    border-radius: 0;
    margin-bottom: -1px;
}
.new_pdf .card-header {
    padding: .75rem 1.25rem;
    margin-bottom: 0;
    background-color: rgba(0,0,0,.03);
    border-bottom: 1px solid rgba(0,0,0,.125);
}

.new_pdf .card-header button{
    font-weight: bold;
    font-size: 15px;
}
.new_pdf ul li{
    list-style:none;
}
.new_pdf a{
color: #007bff !important;
    text-decoration: none;
    background-color: transparent;
    font-size: 16px;
}
.new_pdf a:hover{
color: #0056b3 !important;
}


</style>


<div class="carousel fade-carousel slide new_pdf" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <!-- Indicators -->
   <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1">
          <div class="overlay"></div>
      </div>
      <div class="hero">
        <hgroup>
            <h2>DVV-CRITERIA-7</h2>        
           
        </hgroup>
        
      </div>
    </div>
     </div> 
</div>
       
<div class="container new_pdf" style="box-shadow:-3px 5px 15px #000;     padding: 47px 30px;">
  <!--<ul class="nav nav-tabs" role="tablist" width="90%" style="background-color: #f7f7f7;">-->
  <!--  <li class="nav-item" style="color: rgb(0, 0, 255);">-->
  <!--    <a class="nav-link active" data-toggle="tab" href="NAAC/4.1.1.pdf" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.1.1.1</b></a>-->
  <!--  </li>-->
  <!--  <li class="nav-item">-->
  <!--    <a class="nav-link" data-toggle="tab" href="#menu1" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.2.1</b></a>-->
  <!--  </li>-->
  <!--  <li class="nav-item">-->
  <!--    <a class="nav-link" data-toggle="tab" href="#menu2"><b style="font-size:16px;color:rgb(120, 120, 120)">4.3.1</b></a>-->
  <!--  </li>-->
  <!--   <li class="nav-item">-->
  <!--     </ul>-->
       
 
  <!-- Tab panes -->
   
   
<div class="col-md-12">
    <div class="accordion " id="accordionExample">
       <div class="card">
  
          <div id="collapseCriterionI" class="collapse show" aria-labelledby="headingCriterionI" data-parent="#accordionExample" style="">
             <div class="card-body">
                <div class="accordion" id="accordionExample2">
                   <div class="card">
                      <div class="card-header" id="heading7.1.2">
                         <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse111" aria-expanded="true" aria-controls="collapse111" style="font-weight:bold;font-size:15px;">
                            7.1.2                                </button>
                         </h2>
                      </div>
                      <div id="collapse111" class="collapse" aria-labelledby="heading111" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./DVV/C-7DVV/7.1.2(1).pdf" >7.1.2(1) Geo Tagged Photographs</a></li>
                               <li><a href="./DVV/C-7DVV/7.1.2(2).pdf">7.1.2(2) Invoices </a></li>
                            </ul>
                         </div>
                      </div>
                   </div>
                   <div class="card">
                      <div class="card-header" id="heading7.1.3">
                         <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse121" aria-expanded="true" aria-controls="collapse121" style="font-weight:bold;font-size:15px;">
                            7.1.3                                </button>
                         </h2>
                      </div>
                      <div id="collapse121" class="collapse" aria-labelledby="heading121" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./DVV/C-7DVV/7.1.3(1).pdf" >7.1.3(1) Policy for Energy Utilization and Environment </a></li>
                               <li><a href="./DVV/C-7DVV/7.1.3(2).pdf" >7.1.3(2) Green Audit Report </a></li>
                               <li><a href="./DVV/C-7DVV/7.1.3(3).pdf" >7.1.3(3) Environmental audit (Water & waste management)</a></li>
                               <li><a href="./DVV/C-7DVV/7.1.3(4).pdf" >7.1.3(4) Carbon and Energy Audit</a></li>
                               <li><a href="./DVV/C-7DVV/7.1.3(5).pdf" >7.1.3(5) Document related to clean and Green campus Initiatives</a></li>
                               <li><a href="./DVV/C-7DVV/7.1.3(6).pdf" >7.1.3(6) Report on Green campus Initiatives</a></li>
                               <li><a href="./DVV/C-7DVV/7.1.3(7).pdf" >7.1.3(7) Document related to Environment Promotion Acttivities beyond campus</a></li>
                            </ul>
                         </div>
                      </div>
                   </div>
                   
   
   

    </div>
    </div>

     <div id="menu3" class="container tab-pane fade">
     <!-- <h3>Menu 3</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu4" class="container tab-pane fade">
     <!-- <h3>Menu 4</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu5" class="container tab-pane fade">
     <!-- <h3>Menu 5</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu6" class="container tab-pane fade">
     <!-- <h3>Menu 6</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
  </div>
</div>
<br><br>


<script>
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}
</script>
<?php include 'footer.php';?>