<?php include 'header.php'; ?>
<link  rel="stylesheet" href="./css/custom.css">
<script src="./js/customs.js"></script>



<div class="carousel fade-carousel slide new_pdf" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->
  <!-- Indicators -->
   <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1">
          <div class="overlay"></div>
      </div>
      <div class="hero">
        <hgroup>
            <h2>Extended Profile_DVV</h2>        
           
        </hgroup>
        
      </div>
    </div>
     </div> 
</div>
       
<div class="container new_pdf" style="box-shadow:-3px 5px 15px #000;     padding: 47px 30px;">
  <!--<ul class="nav nav-tabs" role="tablist" width="90%" style="background-color: #f7f7f7;">-->
  <!--  <li class="nav-item" style="color: rgb(0, 0, 255);">-->
  <!--    <a class="nav-link active" data-toggle="tab" href="NAAC/4.1.1.pdf" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.1.1.1</b></a>-->
  <!--  </li>-->
  <!--  <li class="nav-item">-->
  <!--    <a class="nav-link" data-toggle="tab" href="#menu1" ><b style="font-size:16px;color:rgb(120, 120, 120)">4.2.1</b></a>-->
  <!--  </li>-->
  <!--  <li class="nav-item">-->
  <!--    <a class="nav-link" data-toggle="tab" href="#menu2"><b style="font-size:16px;color:rgb(120, 120, 120)">4.3.1</b></a>-->
  <!--  </li>-->
  <!--   <li class="nav-item">-->
  <!--     </ul>-->
       
 
  <!-- Tab panes -->
   
   
<div class="col-md-12">
    <div class="accordion " id="accordionExample">
       <div class="card">
  
          <div id="collapseCriterionI" class="collapse show" aria-labelledby="headingCriterionI" data-parent="#accordionExample" style="">
             <div class="card-body">
                <div class="accordion" id="accordionExample2">
                   <div class="card">
                      <div class="card-header" id="heading1.1">
                         <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse11" aria-expanded="true" aria-controls="collapse11" style="font-weight:bold;font-size:15px;">
                            1.1                                </button>
                         </h2>
                      </div>
                      <div id="collapse11" class="collapse" aria-labelledby="heading11" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./DVV/ExtendedProfile/1.1(1).pdf" >1.1(1)AICTE Approvals for the last five years</a></li>
			                  <li><a href="./DVV/ExtendedProfile/1.1(2).pdf" >1.1(2)List of students for the last five years</a></li>
                            </ul>
                         </div>
                      </div>
                   </div>
                   <div class="card">
                      <div class="card-header" id="heading2.1">
                         <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse21" aria-expanded="true" aria-controls="collapse21" style="font-weight:bold;font-size:15px;">
                            2.1                                </button>
                         </h2>
                      </div>
                      <div id="collapse21" class="collapse" aria-labelledby="heading21" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./DVV/ExtendedProfile/2.1.pdf" >2.1 List of full-time teachers during the last five years without repear count</a></li>
                               </ul>
                         </div>
                      </div>
                   </div>
                   <div class="card">
                      <div class="card-header" id="heading2.2">
                         <h2 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse22" aria-expanded="false" aria-controls="collapse122" style="font-weight:bold;font-size:15px;">
                            2.2                                </button>
                         </h2>
                      </div>
                      <div id="collapse22" class="collapse" aria-labelledby="heading22" data-parent="#accordionExample2" style="">
                         <div class="card-body">
                            <ul>
                               <li><a href="./DVV/ExtendedProfile/2.2.pdf">2.2 List of List of Full-time teachers for the last five years</a></li>
                               </ul>
                         </div>
                      </div>
                   </div>
                   
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
    
     
    <!-- your content -->


 </div>
   
   

    </div>
    </div>

     <div id="menu3" class="container tab-pane fade">
     <!-- <h3>Menu 3</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu4" class="container tab-pane fade">
     <!-- <h3>Menu 4</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu5" class="container tab-pane fade">
     <!-- <h3>Menu 5</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
     <div id="menu6" class="container tab-pane fade">
     <!-- <h3>Menu 6</h3>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>-->
    </div>
  </div>
</div>
<br><br>



<?php include 'footer.php';?>